apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  labels:
    app.kubernetes.io/name: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unpoller
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v2.21.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9130
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config
              mountPath: /etc/unpoller/up.conf
              subPath: up.conf
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: unpoller
