apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-db
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: litellm-db-app
      dataChecksums: true
  enableSuperuserAccess: false
  storage:
    storageClass: truenas-iscsi
    size: 10Gi
    resizeInUseVolumes: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
