apiVersion: v1
kind: Service
metadata:
  name: hwpo-flex
  labels:
    app.kubernetes.io/name: hwpo-flex
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hwpo-flex
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: 8765
      protocol: TCP
