apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - external-secret.yaml
  - pv.yaml
  - pv-truenas.yaml
  - home-assistant.yaml
