apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[email]'
  policy.csv: |
    g, victor@fondevilla.io, role:admin
    g, mcp-user, role:readonly
