apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-google
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: argocd-dex-google
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: dex.google.clientSecret
      remoteRef:
        key: "dex-google-clientSecret"
        property: "password"
