---
# Source: mosquitto/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-2.4.1
---
# Source: mosquitto/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-2.4.1
data:
  mosquitto.conf:
  |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    listener 1883
    listener 9090
    protocol websockets
---
# Source: mosquitto/templates/persistentvolumeclaim.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-2.4.1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
# Source: mosquitto/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-2.4.1
  annotations:
    metallb.universe.tf/allow-shared-ip: "mosquitto"
    metallb.universe.tf/ladBalancerIPs: "10.1.0.204"
spec:
  type: LoadBalancer
  externalTrafficPolicy: 
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: websocket
      port: 9090
      targetPort: websocket
      protocol: TCP
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
---
# Source: mosquitto/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-2.4.1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mosquitto
      annotations:
        checksum/config: b67646920b4371512a37583bf6141685174b7e55d4fae5016b358cd0c37f25b
    spec:
      serviceAccountName: mosquitto
      containers:
        - name: mosquitto
          image: "eclipse-mosquitto:1.6.12"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 5
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
              subPath: 
      volumes:
        - name: config
          configMap:
            name: mosquitto
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"

