apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - ../../base
helmCharts:
  - name: zot
    repo: http://zotregistry.dev/helm-charts
    version: 0.1.122
    releaseName: zot
    namespace: zot
    valuesFile: values.yaml
patches:
  - target:
      kind: Pod
      name: zot-test-connection
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: zot-test-connection
  - target:
      kind: Pod
      name: zot-test-connection-fails
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: zot-test-connection-fails
