apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: librenms
resources:
  - ../../base
helmCharts:
  - name: librenms
    repo: https://www.librenms.org/helm-charts
    version: 8.2.2
    releaseName: librenms
    namespace: librenms
    valuesFile: values.yaml
