apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller
  annotations:
    1password.com/item-uuid: gm422afobjbzdgqwjyze3mh5ni
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: unpoller
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        up.conf: |
          [poller]
            debug = false
            quiet = false
            plugins = []

          [prometheus]
            disable = false
            namespace = "unpoller"
            http_listen = "0.0.0.0:9130"
            report_errors = true

          [influxdb]
            disable = true

          [unifi]
            dynamic = false

          [loki]
            disable = true

          [[unifi.controller]]
            url = "https://10.1.0.1"
            user = "unpoller"
            pass = "{{ .password }}"
            sites = ["all"]
            save_ids = true
            save_dpi = true
            save_sites = true
            hash_pii = false
            verify_ssl = false
  data:
    - secretKey: password
      remoteRef:
        key: Unpoller unifi account
        property: password
