apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.1.0.3
    path: /mnt/flash/k8s_static_pv/mosquitto
  storageClassName: manual
