apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actualbudget

labels:
  - pairs:
      app.kubernetes.io/part-of: actualbudget
    includeSelectors: true

resources:
  - namespace.yaml
  - configmap.yaml
  - pv.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
