apiVersion: v1
data:
  kustomize.buildOptions: --enable-helm
  application.resourceTrackingMethod: annotation
  accounts.mcp-user: apiKey
  url: https://argo.cp.fondevilla.io
  dex.config: |
    connectors:
    - type: google
      id: google
      name: Google
      config:
        clientID: 412166888354-dtg2bn7r93omr3e32kaoob9g8c9riim5.apps.googleusercontent.com
        clientSecret: $argocd-dex-google:dex.google.clientSecret
        redirectURI: https://argo.cp.fondevilla.io/api/dex/callback
        hostedDomains:
        - fondevilla.io
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
