apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-cluster-workload-cluster
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: workload-cluster
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          type: workload
          cluster: workload
      data:
        name: workload-cluster
        server: "{{ .server }}"
        config: |
          {
            "bearerToken": "{{ .bearerToken }}",
            "tlsClientConfig": {
              "insecure": true
            }
          }
  data:
    - secretKey: server
      remoteRef:
        key: argocd-cluster-workload-cluster
        property: server
    - secretKey: bearerToken
      remoteRef:
        key: argocd-cluster-workload-cluster
        property: bearerToken
