apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
      path: k8s/loki
      directory:
        recurse: true
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
