apiVersion: v1
kind: PersistentVolume
metadata:
  name: meshcentral-data
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteMany"]
  storageClassName: manual
  nfs:
    server: nas02.fondevilla.io
    path: "/mnt/SSD/k8s_static_pv/meshcentral/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meshcentral-files
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteMany"]
  storageClassName: manual
  nfs:
    server: nas02.fondevilla.io
    path: "/mnt/SSD/k8s_static_pv/meshcentral/files"
