apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-iscsi-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: truenas-iscsi-driver-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        driver-config-file.yaml: |-
          driver: freenas-api-iscsi
          instance_id: control-plane-iscsi
          httpConnection:
            protocol: https
            host: 10.1.0.4
            port: 4443
            apiKey: "{{ .apiKey }}"
            allowInsecure: true
            apiVersion: 2
          zfs:
            datasetParentName: SSD/democratic-csi/control-plane/iscsi
            detachedSnapshotsDatasetParentName: SSD/democratic-csi/control-plane/iscsi-snapshots
            zvolCompression: lz4
            zvolEnableReservation: false
            zvolBlocksize: 16K
          iscsi:
            targetPortal: 10.254.0.4:3260
            targetPortals: []
            interface: ""
            namePrefix: csi-cp-
            nameSuffix: ""
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup: null
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: SSD
            extentAvailThreshold: 0
  data:
    - secretKey: apiKey
      remoteRef:
        key: truenas democratic csi api token
        property: password
