apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cloudflare-externaldns
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
