router bgp 65000
  bgp bestpath as-path multipath-relax
  no bgp ebgp-requires-policy
  bgp router-id 10.1.0.1
  neighbor control-cluster peer-group
  neighbor control-cluster remote-as external
  neighbor 10.1.0.10 peer-group control-cluster