apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - ../../base
helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 8.3.0
    releaseName: velero
    namespace: velero
    valuesFile: values.yaml
