apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: log-collector
  ports:
    - name: http-metrics
      port: 3101
      targetPort: http-metrics
      protocol: TCP
