apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
      path: k8s/cert-manager
      directory:
        recurse: true
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
