apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd 
spec:
  destination:
    namespace: cert-manager 
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    targetRevision: 1.14.4
    chart: cert-manager
    helm:
      valuesObject:
        installCRDs: true
        prometheus:
          servicemonitor:
            enabled: true
  - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
    path: k8s/cert-manager/
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true