apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: netshoot-hostnetwork
    namespace: kube-system
spec:
    selector:
        matchLabels:
            app: netshoot
    template:
        metadata:
            labels:
                app: netshoot
        spec:
            hostNetwork: true
            containers:
                - name: netshoot
                  image: nicolaka/netshoot
                  command:
                    - sleep
                    - infinity
