apiVersion: v1
kind: Pod
metadata:
    name: disk-wipe
    # Use a privileged namespace if needed
    namespace: kube-system
spec:
    hostPID: true
    hostNetwork: true
    containers:
        - name: disk-wipe
          image: busybox
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - dd if=/dev/zero of=/dev/nvme2n1 bs=512 count=1
          volumeMounts:
            - name: dev
              mountPath: /dev
    volumes:
        - name: dev
          hostPath:
            path: /dev
    restartPolicy: Never
    nodeSelector:
        kubernetes.io/hostname: node07
