apiVersion: v1
kind: Pod
metadata:
    name: disk-wipe
    # Use a privileged namespace if needed
    namespace: rook-ceph
spec:
    hostPID: true
    hostNetwork: true
    containers:
        - name: disk-wipe
          image: busybox
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - dd if=/dev/zero of=/dev/nvme0n1 bs=512 count=1
          volumeMounts:
            - name: dev
              mountPath: /dev
    volumes:
        - name: dev
          hostPath:
            path: /dev
    restartPolicy: Never
    nodeSelector:
        kubernetes.io/hostname: node08
sops:
    age:
        - recipient: age1mj0dy50zdfyxkwd2av4jf3hn9zgpxn9rukypgv2976zd6al234zsm68f0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY1IxTnZIVlRvSndsMWJy
            OUZ2UTQvQ2x3TEt1K1h3SXI5SUUvVEg2cHprClNYOGsydnpoYmd1VjVvNVV4VE1L
            MjA0KzJXenh0Z0wxMCtITFhvWTVPNncKLS0tIGdjSzUzbzMzUVlBWVhINFkyWjlC
            bllCVXdmSC9MbUErTUF2ZW1aL2tUOWcK1Fa6mSexiycPbiA4m4PjAr+rOcaUDs/m
            YFSu0FdZE2EySA5GFrbe6o32ACpUmjKoMGdakKVvFd/GJkP2gF2Uhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T08:22:25Z"
    mac: ENC[AES256_GCM,data:3A2gbYJecnRa6QqPQp48iSDFWBDgpqZIwd4kpQreR0FRGTMMuC+n3gLRGuVfJm2f5pUTF1Bt4kulZTAb1ifLB5qUNuEa6q/xwpNdunLM0rwvXvm6weJRCNasQ0YL6La6k9tZg/SRoxo/+C5Vud78MITzsB9iVEGr7fRdF2Rrzcw=,iv:hkZgNHnuD+I7NfchEwntUzGhhiszRQNTgggzxJz1ru4=,tag:U8Ts3z/ZKRDcKbvpGinMtA==,type:str]
    encrypted_regex: ^(token|key)$
    mac_only_encrypted: true
    version: 3.10.2
