apiVersion: v1
data:
  kustomize.buildOptions: --enable-helm
  application.resourceTrackingMethod: annotation
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd

