apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: chatgpt/gpt-5.6-sol
        model_info:
          mode: responses
        litellm_params:
          model: chatgpt/gpt-5.6-sol
      - model_name: chatgpt/gpt-5.6-luna
        model_info:
          mode: responses
        litellm_params:
          model: chatgpt/gpt-5.6-luna
      - model_name: chatgpt/gpt-5.6-terra
        model_info:
          mode: responses
        litellm_params:
          model: chatgpt/gpt-5.6-terra
      - model_name: local/Qwen3.6
        litellm_params:
          model: unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
          api_base: http://llm01.fondevilla.io:8080/v1
          api_key: local-no-auth


    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
      database_url: os.environ/DATABASE_URL
      store_model_in_db: true
      store_prompts_in_spend_logs: true

    litellm_settings:
      drop_params: true
      telemetry: false
