apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    model_list:
      - model_name: local/Qwen3.8-Flash-Next
        litellm_params:
          model: openai/halogen-qwen3.8-flash-next
          api_base: http://llm01.fondevilla.io:8731/v1
          api_key: local-no-auth


    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
      database_url: os.environ/DATABASE_URL
      store_model_in_db: true
      store_prompts_in_spend_logs: true

    litellm_settings:
      drop_params: true
      telemetry: false
