apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: litellm-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: master-key
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: salt-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db-app
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: litellm-db-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        uri: "postgresql://{{ .username | urlquery }}:{{ .password | urlquery }}@litellm-db-rw.litellm.svc.cluster.local:5432/litellm?schema=public&sslmode=require"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-database
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: litellm-database
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
