apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: litellm-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: litellm
        property: master-key
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: litellm
        property: salt-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db-app
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: litellm-db-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: litellm-database
        property: username
    - secretKey: password
      remoteRef:
        key: litellm-database
        property: password
    - secretKey: uri
      remoteRef:
        key: litellm-database
        property: uri
