apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Tailscale Oauth K8s Operator
        metadataPolicy: None
        property: username
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Tailscale Oauth K8s Operator
        metadataPolicy: None
        property: credential
