apiVersion: v1
kind: Service
metadata:
  name: meshcentral
  annotations:
    external-dns.alpha.kubernetes.io/hostname: meshcentral.fondevilla.io
spec:
  type: LoadBalancer
  selector:
    app: meshcentral
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: intel-amt
      port: 4433
      targetPort: 4433
      protocol: TCP
