# https://taskfile.dev
version: "3"
vars:
    GREETING: Hello, World!
tasks:
    default:
        cmds:
            - echo "{{.GREETING}}"
        silent: true
    encrypt:
        cmds:
            - find . -type f -name "*.yaml" -exec sops encrypt -i {} \;
