apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant
  namespace: argocd
spec:
  description: Applications for registered tenant clusters
  sourceRepos:
    - git@github.com:vFondevilla/k8s-homelab.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
