apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-nfs-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: truenas-nfs-driver-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        driver-config-file.yaml: |-
          driver: freenas-api-nfs
          instance_id: workload-nfs
          httpConnection:
            protocol: https
            host: 10.1.0.4
            port: 4443
            apiKey: "{{ .apiKey }}"
            allowInsecure: true
            apiVersion: 2
          zfs:
            datasetParentName: SSD/democratic-csi/workload/nfs
            detachedSnapshotsDatasetParentName: SSD/democratic-csi/workload/nfs-snapshots
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareHost: 10.254.0.4
            shareAlldirs: false
            shareAllowedHosts:
              - 10.254.0.17
              - 10.254.0.18
              - 10.254.0.19
            shareAllowedNetworks: []
            shareMaprootUser: root
            shareMaprootGroup: root
            shareMapallUser: ""
            shareMapallGroup: ""
  data:
    - secretKey: apiKey
      remoteRef:
        key: truenas democratic csi api token
        property: password
