apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-chatgpt-auth-nfs-client
  namespace: litellm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
