apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-master-key
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: litellm-master-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        masterkey: "sk-{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: litellm-master-key
        property: password
