apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: postgres
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: litellm-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: litellm-postgres
        property: password
