apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.1.0.4
    path: "/mnt/SSD/k8s_static_pv/zigbee2mqtt"
  storageClassName: manual