kind: PersistentVolume
apiVersion: v1
metadata:
  name: omni-etcd-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/flash/k8s_static_pv/omni/
    server: 10.1.0.3
