apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ip-pool.yaml
helmCharts:
  - name: stack
    repo: oci://ghcr.io/tinkerbell/charts/tinkerbell
    version: 0.22.1
    releaseName: tinkerbell
    namespace: tinkerbell
    valuesFile: values.yaml
