apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 1p
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
  sources:
    - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
      path: k8s/1password-connect
      directory:
        recurse: true
      targetRevision: HEAD
