apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://k8s.fondevilla.io:6443
  project: default
  sources:
    - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
      path: k8s/1-workload-cluster/multus
      directory:
        recurse: true
      targetRevision: HEAD