apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt
data:
  configuration.yaml: |
    devices: devices.yaml
    groups: groups.yaml
    homeassistant:
      discovery_topic: homeassistant
      enabled: true
      legacy_entity_attributes: true
      legacy_triggers: false
      status_topic: hass/status
    ota:
      disable_automatic_update_check: false
      ikea_ota_use_test_url: false
      update_check_interval: 1440
    permit_join: true
    blocklist: []
    availability:
      active:
        timeout: 10
      passive:
        timeout: 1500
    mqtt:
      server: mqtt://mosquitto.mosquitto.svc.cluster.local
    serial:
      baudrate: 115200
      port: tcp://10.1.0.140:6638
      adapter: ember
    frontend:
      host: 0.0.0.0
      port: 8080
    advanced:
      cache_state: true
      cache_state_persistent: true
      cache_state_send_on_startup: true
      channel: 25
      elapsed: false
      last_seen: disable
      legacy_api: false
      log_level: info
      log_output:
        - console
      report: true
      timestamp_format: YYYY-MM-DD HH:mm:ss
      transmit_power: 20
