apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: z2m

resources:
  - namespace.yaml
  - pv.yaml
  - configmap.yaml
  - service.yaml
  - statefulset.yaml

images:
  - name: koenkk/zigbee2mqtt
    newTag: 2.10.1
