apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
  namespace: external-secrets
spec:
  provider:
    onepassword:
      vaults:
        lab: 1
      auth:
        serviceAccountToken:
          secretRef:
            name: onepassword-sa-token
            key: token
            namespace: external-secrets
