apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbootxyz
  namespace: argocd 
spec:
  destination:
    namespace: netbootxyz
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
      path: k8s/netboot
      directory:
        recurse: true
      targetRevision: HEAD

  syncPolicy:
    # automated: {}
    syncOptions:
    - CreateNamespace=true