apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt-net
  namespace: argocd 
spec:
  destination:
    namespace: z2m
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.zigbee2mqtt.io
    targetRevision: 2.1.1
    chart: zigbee2mqtt
    helm:
      valuesObject:
        # customLabels:
        #   pod-security.kubernetes.io/enforce: privileged
        image:
          tag: 1.42.0
        statefulset:
          storage:
            enabled: true
            size: 2Gi
            storageClassName: rook-ceph-block
        zigbee2mqtt:
          serial:
            port: tcp://10.1.0.140:6638
            adapter: ember
            baudrate: 115200
            advanced:
              transmit_power: 20
          permit_join: true
          mqtt:
            server: "mqtt://mosquitto.mosquitto.svc.cluster.local"
          advanced:
            channel: 25
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: zigbee2mqtt.apps.fondevilla.io
              paths:
                - path: /
                  pathType: ImplementationSpecific
                - path: /api
                  pathType: ImplementationSpecific
  # - repoURL: 'git@github.com:vFondevilla/k8s-homelab.git'
  #   path: k8s/zigbee2mqtt
  #   targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true