apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 1p
resources:
  - namespace.yaml
secretGenerator:
  - name: op-credentials
    namespace: 1p
    files:
      - 1password-credentials.json
    options:
      disableNameSuffixHash: true
