---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mini
  namespace: default
spec:
  endpoints:
  - dnsName: mini.fondevilla.io
    recordTTL: 300
    recordType: A
    targets:
      - 10.1.0.107