apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-minio-secret
  namespace: loki
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: accessKeyId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: minio-loki
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: secretAccessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: minio-loki
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
