apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kamaji-kubevirt-class
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:vFondevilla/k8s-homelab.git
    path: k8s/fleet/classes/kamaji-kubevirt
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
