apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: kro
    repo: oci://registry.k8s.io/kro/charts
    version: 0.9.3
    releaseName: kro
    namespace: kro-system
    includeCRDs: true
